// constants/index.ts
export const projectsList = [
  {
    id: 1,
    title: "Monster Pedia",
    description: "Website containing a pokedex, a type calculator, a team builder, and a card generator.",
    logo: "/projects/monsterpedia.ico",
    link: "https://monsterpedia-orcin.vercel.app/",
    github: "https://github.com/MihirJaiswal/monsterpedia",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 2,
    title: "Ink Scroll",
    description: "Manga Hosting website where users can upload and read mangas.",
    logo: "/projects/inkscroll.png",
    link: "https://www.youtube.com/watch?v=uP-OGbNdiZI",
    github: "https://github.com/MihirJaiswal/InkScroll",
    technologies: ["Next.js", "Node.js", "TypeScript"],
  },
  {
    id: 3,
    title: "HERO-HQ",
    description: "Web application where users can explore details about various superheroes and compare.",
    logo: "/projects/herohq.png",
    link: "https://hero-hq-five.vercel.app/",
    github: "https://github.com/MihirJaiswal/hero-hq",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 4,
    title: "Ghibli Verse",
    description: "A comprehensive web application dedicated to exploring the enchanting world of Studio Ghibli.",
    logo: "/projects/ghibli.ico",
    link: "https://ghibli-verse.vercel.app/",
    github: "https://github.com/MihirJaiswal/ghibli-verse",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 5,
    title: "CyberSphere",
    description: "CyberSphere is a browser extension and website designed to detect phishing attacks.",
    logo: "/projects/cybersphere.png",
    link: "https://cyber-sphere-minor-project.vercel.app/",
    github: "https://github.com/MihirJaiswal/CyberSphere-Minor-Project",
    technologies: ["React", "Tailwind", "M.L."],
  },
  {
    id: 6,
    title: "GDSC CDGI Website",
    description: "The official website of GDSC CDGI.",
    logo: "/projects/gdsc.svg",
    link: "https://github.com/gdscwebsite",
    github: "https://github.com/gdscwebsite",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 7,
    title: "Toy Sandook",
    description: "Toy Sandook is a website that I made for a client.",
    logo: "/projects/toy.png",
    link: "https://github.com/MihirJaiswal/toyshopweb",
    github: "https://github.com/MihirJaiswal/toyshopweb",
    technologies: ["Next.js", "MongoDB", "Express",],
  },
  {
    id: 8,
    title: "Flex Hub",
    description: "Flex Hub is a gym website that I made for a client. I used TypeScript and Tailwind CSS for it.",
    logo: "/projects/flexhub.png",
    link: "https://github.com/MihirJaiswal/Flex-Hub",
    github: "https://github.com/MihirJaiswal/Flex-Hub",
    technologies: ["React", "Tailwind", "TypeScript"],
  },
  {
    id: 9,
    title: "Citronics Website",
    description: "Citronics is an annual techno-management fest of CDGI, Indore.",
    logo: "/projects/citro.png",
    link: "https://mihirjaiswal.github.io/Citronics-website2024/",
    github: "https://github.com/MihirJaiswal/Citronics-website2024",
    technologies: ["HTML", "Tailwind", "JavaScript"],
  },
  {
    id: 10,
    title: "GCSJ Certificate Generator",
    description: "A certificate generator for participants who successfully completed the Google Cloud Study Jams tasks.",
    logo: "/projects/gdsc.svg",
    link: "https://certificate-generator-chi.vercel.app/",
    github: "https://github.com/MihirJaiswal/certificate-generator",
    technologies: ["React", "SCSS"],
  },
  {
    id: 11,
    title: "Dream Mist",
    description: "Dream Mist is a Pokémon game made using HTML canvas.",
    logo: "/projects/dreammist.jpg",
    link: "https://mihirjaiswal.github.io/DreamMist/",
    github: "https://github.com/MihirJaiswal/DreamMist",
    technologies: ["HTML","JavaScript", "CSS"],
  },
  {
    id: 12,
    title: "Cosmic Onslaught",
    description: "Cosmic Onslaught is a classic space invader game brought to life with HTML, CSS, and JavaScript.",
    logo: "/projects/cosmic.png",
    link: "https://mihirjaiswal.github.io/Cosmic-Onslaught/",
    github: "https://github.com/MihirJaiswal/Cosmic-Onslaught",
    technologies: ["HTML","JavaScript", "CSS"],
  },
];

  