// constants/index.ts
export const projectsList = [
  {
    id: 1,
    title: "Monster Pedia",
    description: "Website containing a pokedex, a type calculator, a team builder, and a card generator.",
    logo: "/projects/monsterpedia.ico",
    link: "https://monsterpedia-orcin.vercel.app/",
    github: "https://github.com/MihirJaiswal/monsterpedia",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 2,
    title: "Ink Scroll",
    description: "Manga Hosting website where users can upload and read mangas.",
    logo: "/projects/inkscroll.png",
    link: "https://www.youtube.com/watch?v=uP-OGbNdiZI",
    github: "https://github.com/MihirJaiswal/InkScroll",
    technologies: ["Next.js", "Node.js", "TypeScript"],
  },
  {
    id: 3,
    title: "HERO-HQ",
    description: "Web application where users can explore details about various superheroes and compare.",
    logo: "/projects/herohq.png",
    link: "https://hero-hq-five.vercel.app/",
    github: "https://github.com/MihirJaiswal/hero-hq",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 4,
    title: "Ghibli Verse",
    description: "A comprehensive web application dedicated to exploring the enchanting world of Studio Ghibli.",
    logo: "/projects/ghibli.ico",
    link: "https://ghibli-verse.vercel.app/",
    github: "https://github.com/MihirJaiswal/ghibli-verse",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 5,
    title: "CyberSphere",
    description: "CyberSphere is a browser extension and website designed to detect phishing attacks.",
    logo: "/projects/cybersphere.png",
    link: "https://cyber-sphere-minor-project.vercel.app/",
    github: "https://github.com/MihirJaiswal/CyberSphere-Minor-Project",
    technologies: ["React", "Tailwind", "M.L."],
  },
  {
    id: 6,
    title: "GDSC CDGI Website",
    description: "The official website of GDSC CDGI.",
    logo: "/projects/gdsc.svg",
    link: "https://github.com/gdscwebsite",
    github: "https://github.com/gdscwebsite",
    technologies: ["Next.js", "Tailwind", "TypeScript"],
  },
  {
    id: 7,
    title: "Toy Sandook",
    description: "Toy Sandook is a website that I made for a client.",
    logo: "/projects/toy.png",
    link: "https://github.com/MihirJaiswal/toyshopweb",
    github: "https://github.com/MihirJaiswal/toyshopweb",
    technologies: ["Next.js", "MongoDB", "Express",],
  },
  {
    id: 8,
    title: "Flex Hub",
    description: "Flex Hub is a gym website that I made for a client. I used TypeScript and Tailwind CSS for it.",
    logo: "/projects/flexhub.png",
    link: "https://github.com/MihirJaiswal/Flex-Hub",
    github: "https://github.com/MihirJaiswal/Flex-Hub",
    technologies: ["React", "Tailwind", "TypeScript"],
  },
  {
    id: 9,
    title: "Citronics Website",
    description: "Citronics is an annual techno-management fest of CDGI, Indore.",
    logo: "/projects/citro.png",
    link: "https://mihirjaiswal.github.io/Citronics-website2024/",
    github: "https://github.com/MihirJaiswal/Citronics-website2024",
    technologies: ["HTML", "Tailwind", "JavaScript"],
  },
  {
    id: 10,
    title: "GCSJ Certificate Generator",
    description: "A certificate generator for participants who successfully completed the Google Cloud Study Jams tasks.",
    logo: "/projects/gdsc.svg",
    link: "https://certificate-generator-chi.vercel.app/",
    github: "https://github.com/MihirJaiswal/certificate-generator",
    technologies: ["React", "SCSS"],
  },
  {
    id: 11,
    title: "Dream Mist",
    description: "Dream Mist is a Pokémon game made using HTML canvas.",
    logo: "/projects/dreammist.jpg",
    link: "https://mihirjaiswal.github.io/DreamMist/",
    github: "https://github.com/MihirJaiswal/DreamMist",
    technologies: ["HTML","JavaScript", "CSS"],
  },
  {
    id: 12,
    title: "Cosmic Onslaught",
    description: "Cosmic Onslaught is a classic space invader game brought to life with HTML, CSS, and JavaScript.",
    logo: "/projects/cosmic.png",
    link: "https://mihirjaiswal.github.io/Cosmic-Onslaught/",
    github: "https://github.com/MihirJaiswal/Cosmic-Onslaught",
    technologies: ["HTML","JavaScript", "CSS"],
  },
];


export const skills = [
  {
    name: "Next.js",
    description: "Web development",
    link: "https://nextjs.org/", // Updated link
    type: "development",
    image: '/skills/nextjs.png'
  },
  {
    name: "React",
    description: "Web development",
    link: "https://reactjs.org/",
    type: "development",
    image: '/skills/react.png'
  },
  {
    name: "Tailwind",
    description: "Web development",
    link: "https://tailwindcss.com/",
    type: "design",
    image: '/skills/tailwind.svg'
  },
  {
    name: "Sass",
    description: "Web development, styling",
    link: "https://sass-lang.com/",
    type: "design",
    image: '/skills/sass.svg'
  },
  {
    name: "Javascript",
    description: "Web development",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    type: "development",
    image: '/skills/javascript.png'
  },
  {
    name: "Typescript",
    description: "Web development",
    link: "https://www.typescriptlang.org/",
    type: "development",
    image: '/skills/typescript.png'
  },
  {
    name: "Html5",
    description: "Web layouts",
    link: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
    type: "development",
    image: '/skills/html-5.png'
  },
  {
    name: "Css3",
    description: "Web design",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    type: "design",
    image: '/skills/css3.png'
  },
  {
    name: "MongoDB",
    description: "Database",
    link: "https://www.mongodb.com/",
    type: "database",
    image: '/skills/mongodb.svg'
  },
  {
    name: "Mysql",
    description: "Database",
    link: "https://www.mysql.com/",
    type: "database",
    image: '/skills/mysql.png'
  },
  {
    name: "Vercel",
    description: "Deployment platform",
    link: "https://vercel.com/",
    type: "devops",
    image: '/skills/vercel.png'
  },
  {
    name: "AWS",
    description: "Cloud computing",
    link: "https://aws.amazon.com/",
    type: "devops",
    image: '/skills/aws.png'
  },
  {
    name: "Express",
    description: "Web application framework",
    link: "https://expressjs.com/",
    type: "development",
    image: '/skills/express.png'
  },
  {
    name: "Visual Studio Code",
    description: "Code editor of choice",
    link: "https://code.visualstudio.com/",
    type: "",
    image: '/skills/vscode.png'
  },
  {
    name: "Canva",
    description: "Designing and editing",
    link: "https://www.canva.com/",
    type: "design",
    image: '/skills/canva.svg'
  },
  {
    name: "Figma",
    description: "Collaborative Design",
    link: "https://www.figma.com/",
    type: "design",
    image: '/skills/figma.png'
  }
];


export const PREDEFINED_QA = [
  { question: "What is your name?", answer: "My name is Mihir." },
  { question: "What do you do?", answer: "I'm a Full Stack Developer and UI/UX Designer." },
  { question: "What are your hobbies?", answer: "I enjoy playing video games, drawing, cooking, and reading." },
  { question: "Where are you from?", answer: "I'm from India." },
  { question: "How old are you?", answer: "I'm in my early 20s." },
  { question: "What is your favorite color?", answer: "My favorite color is blue." },
  { question: "What is your favorite food?", answer: "I love pizza." },
  { question: "Do you like to travel?", answer: "Yes, I enjoy traveling to new places." },
  { question: "What is your favorite movie?", answer: "My favorite movie is 'Inception'." },
  { question: "What kind of music do you like?", answer: "I enjoy listening to a variety of music genres." },
  { question: "Do you play any musical instruments?", answer: "No, I don't play any musical instruments." },
  { question: "What languages do you speak?", answer: "I speak English and Hindi." },
  { question: "Do you have any pets?", answer: "No, I don't have any pets." },
  { question: "What is your favorite book?", answer: "My favorite book is 'To Kill a Mockingbird'." },
  { question: "What sports do you like?", answer: "I enjoy watching boxing and cricket sometimes." },
  { question: "Do you work out?", answer: "Yes, I try to stay active." },
  { question: "What is your favorite season?", answer: "My favorite season is winter." },
  { question: "Do you like coffee or tea?", answer: "I prefer coffee." },
  { question: "Are you a morning person or a night owl?", answer: "I'm more of a night owl." },
  { question: "What is your dream job?", answer: "My dream job is to be a tech entrepreneur." },
  { question: "Do you have any siblings?", answer: "Yes, I have siblings." },
  { question: "What is your favorite holiday?", answer: "My favorite holiday is Diwali." },
  { question: "What is your favorite TV show?", answer: "I enjoy watching 'Stranger Things'." },
  { question: "Do you prefer cats or dogs?", answer: "I like cats." },
  { question: "What is your favorite ice cream flavor?", answer: "I love chocolate ice cream." },
  { question: "What is your favorite place to visit?", answer: "I enjoy visiting the mountains." },
  { question: "Do you like to cook?", answer: "Yes, I enjoy cooking." },
  { question: "What is your favorite dessert?", answer: "My favorite dessert is cheesecake." },
  { question: "Do you play any sports?", answer: "I play badminton occasionally." },
  { question: "What is your favorite video game?", answer: "I enjoy playing 'The Legend of Zelda' series." },
  { question: "Do you like art?", answer: "Yes, I love art and drawing." },
  { question: "Do you prefer movies or TV shows?", answer: "I like both, but I usually watch more TV shows." },
  { question: "What is your favorite kind of weather?", answer: "I like cool, breezy weather." },
  { question: "What is your favorite subject in school?", answer: "I enjoyed studying computer science." },
  { question: "Do you like to read?", answer: "Yes, I enjoy reading." },
  { question: "What is your favorite animal?", answer: "My favorite animal is the dolphin." },
  { question: "Do you like to dance?", answer: "I'm not much of a dancer." },
  { question: "Do you like to sing?", answer: "I enjoy singing occasionally, but I'm not very good at it." },
  { question: "What is your favorite drink?", answer: "My favorite drink is coffee." },
  { question: "What is your favorite time of day?", answer: "I enjoy the evening." },
  { question: "Do you prefer sweet or savory foods?", answer: "I prefer savory foods." },
  { question: "Do you like to go to the beach?", answer: "Yes, I love going to the beach." },
  { question: "What is your favorite kind of movie?", answer: "I enjoy sci-fi and action movies." },
  { question: "Do you like to garden?", answer: "I don't garden, but I appreciate plants." },
  { question: "Do you like to write?", answer: "Yes, I enjoy writing stories." },
  { question: "What is your favorite type of exercise?", answer: "I enjoy going for a run." },
  { question: "Do you like to paint?", answer: "Yes, I enjoy painting." },
  { question: "Do you have any allergies?", answer: "No, I don't have any allergies." },
  { question: "What is your favorite fruit?", answer: "My favorite fruit is mango." },
  { question: "Do you like to swim?", answer: "Yes, I enjoy swimming." },
  { question: "What is your favorite type of cuisine?", answer: "I love Italian cuisine." },
  { question: "Do you like to do puzzles?", answer: "Yes, I enjoy solving puzzles." },
  { question: "Do you like to watch sports?", answer: "Yes, I like watching football." },
  { question: "What is your favorite candy?", answer: "I love chocolate bars." },
  { question: "Do you like to go camping?", answer: "Yes, I enjoy camping." },
  { question: "What is your favorite holiday destination?", answer: "I love visiting the mountains." },
  { question: "Do you like to bake?", answer: "Yes, I enjoy baking." },
  { question: "Do you like board games?", answer: "Yes, I enjoy playing board games." },
  { question: "What is your favorite hobby?", answer: "I enjoy drawing and coding." },
  { question: "Do you like museums?", answer: "Yes, I enjoy visiting museums." },
  { question: "Do you like roller coasters?", answer: "Yes, I enjoy roller coasters." },
  { question: "What is your favorite ice cream topping?", answer: "I like chocolate chips as a topping." },
  { question: "Do you like scary movies?", answer: "Yes, I enjoy a good horror movie now and then." },
  { question: "What is your favorite vegetable?", answer: "My favorite vegetable is spinach." },
  { question: "Do you like the city or countryside?", answer: "I enjoy the peace of the countryside." },
  { question: "What is your favorite sandwich?", answer: "I love a classic grilled cheese sandwich." },
  { question: "Do you like to shop?", answer: "Yes, I enjoy shopping occasionally." },
  { question: "Do you prefer chocolate or vanilla?", answer: "I prefer chocolate." },
  { question: "Do you like rain or sunshine?", answer: "I like sunshine, but I also enjoy the rain." },
  { question: "What is your favorite quote?", answer: "My favorite quote is 'The only limit to our realization of tomorrow is our doubts of today.'" },
  { question: "Do you like to do yoga?", answer: "Yes, I enjoy doing yoga." },
  { question: "Do you like to play cards?", answer: "Yes, I enjoy playing cards." },
  { question: "What is your favorite flower?", answer: "My favorite flower is the rose." },
  { question: "Do you like to hike?", answer: "Yes, I enjoy hiking." },
  { question: "Do you like to go to concerts?", answer: "Yes, I enjoy live music." },
  { question: "What is your favorite snack?", answer: "I like popcorn as a snack." },
  { question: "Do you like to go to the gym?", answer: "Yes, I try to stay active." },
  { question: "Do you like to eat out?", answer: "Yes, I enjoy trying new restaurants." },
  { question: "What is your favorite drink?", answer: "My favorite drink is coffee." },
  { question: "Do you like to play video games?", answer: "Yes, I love playing video games." },
  { question: "What is your favorite TV channel?", answer: "I usually watch Netflix or streaming services." },
  { question: "Do you like to do crafts?", answer: "Yes, I enjoy doing DIY crafts." },
  { question: "What is your favorite park?", answer: "I enjoy visiting national parks." },
  { question: "Do you like to read magazines?", answer: "Yes, I occasionally read magazines." },
  { question: "What is your favorite season?", answer: "I enjoy the winter season." },
  { question: "Do you like to play chess?", answer: "Yes, I enjoy playing chess." },
  { question: "What is your favorite fast food?", answer: "I love burgers." },
  { question: "Do you like to watch cartoons?", answer: "Yes, I still enjoy watching cartoons." },
  { question: "Do you like to fish?", answer: "Yes, I enjoy fishing." },
  { question: "What is your favorite place to relax?", answer: "I enjoy relaxing at the beach." },
  { question: "Do you like to go to the zoo?", answer: "Yes, I enjoy visiting the zoo." },
  { question: "Do you like spicy food?", answer: "Yes, I enjoy spicy food." },
  { question: "Do you like to ride bikes?", answer: "Yes, I enjoy biking." },
  { question: "What is your favorite vacation spot?", answer: "I love visiting the mountains." },
  { question: "Do you like to go to the movies?", answer: "Yes, I enjoy going to the movies." },
  { question: "Do you like to eat breakfast?", answer: "Yes, breakfast is my favorite meal of the day." },
  
];

